# Generated by Django 6.1.1 on 2026-10-05 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vehicles_DB',
            fields=[
                ('reg_no', models.TextField()),
                ('vehicle_model_name', models.CharField(max_length=32)),
                ('owner_name', models.CharField(max_length=32)),
                ('owner_Email', models.EmailField(max_length=254)),
                ('owner_contact_no', models.IntegerField()),
                ('owner_Address', models.TextField()),
                ('dl_no', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
